### ISSUE TITLE
当前账号已在别处登录，请重新登录进入选课

### ISSUE THREAD

**Issue by kitzza** [HuaHuaY/SUSTech-CaptureClass#1]
upup，请问出现了，【当前账号已在别处登录，请重新登录进入选课】。请问咋解决的呀。  

我访问了 session.get(base_url + k, headers=headers, verify=False)  还是显示，未登录

![image](https://github.com/user-attachments/assets/02ff4f05-43d7-4a0a-b98d-fc34db07458d)

**Comment by HuaHuaY** [comment]
已经毕业几年了，不太清楚现在校内的情况，不再维护这个repo
